package:
  name: kinomodel
  version: "0.0.0"

source:
  path: ../..

build:
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - openmm
    - numpy
    - mdtraj
    - requests
    - pdbfixer
    - pypdb
    - xmltodict

test:
  requires:
    - pytest
  imports:
    - kinomodel

about:
  home: http://github.com/inspiremd/kinomodel
  license: MIT
  license_file: LICENSE
